/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PlagiarismCheckerSwing;
import com.plagiarismchecker.api.client.PlagiarismCheckerClient;
import com.plagiarismchecker.api.client.PlagiarismCheckerConfig;
import com.plagiarismchecker.api.client.PlagiarismCheckerResponse;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
