/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package let.me.know.my.note;

import java.awt.Color;
import java.awt.Toolkit;

/**
 *
 * @author Yahia Benotmane
 */
public class DEP extends javax.swing.JFrame {

    /**
     * Creates new form HOME
     */
    public DEP() {
        
        initComponents();
        
        this.setLocationRelativeTo(this);
        SetIconImage();
        general_panel.setVisible(true);
        GPanel_First.setVisible(true);
        GPanel_help.setVisible(false);
        GPanel_second.setVisible(false);
        
        
        //Tools panel colors
        Tool_Panel_home.setBackground(new java.awt.Color(255,255,255));
        Tool_Panal_Second.setBackground(new java.awt.Color(204,204,255));
        Tool_Panal_help.setBackground(new java.awt.Color(204,204,255));
        //Panel4.setBackground(new java.awt.Color(204,204,255));
        Tool_panal_exit.setBackground(new java.awt.Color(204,204,255));
        //Pnanal colors
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        general_panel = new javax.swing.JPanel();
        GPanel_First = new javax.swing.JPanel();
        btnSAVEGeneral = new javax.swing.JButton();
        btnUPDATECLASS = new javax.swing.JButton();
        btnSerachSOMEONE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        GENERALjTable1 = new javax.swing.JTable();
        SEARCHTextField1 = new javax.swing.JTextField();
        CLASSOFjTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SEARCHSOMEONEjLabel6 = new javax.swing.JLabel();
        GPanel_help = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        GPanel_second = new javax.swing.JPanel();
        jPanelClass = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TECHERjTable = new javax.swing.JTable();
        btnEDITTECHER = new javax.swing.JButton();
        btnUPLOADTEACHER = new javax.swing.JButton();
        CLASSjLabel = new javax.swing.JLabel();
        jPaneltecher = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        MODULESjTable3 = new javax.swing.JTable();
        btnupdate = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        MODULESjLabel10 = new javax.swing.JLabel();
        jTextFieldsearch = new javax.swing.JTextField();
        btnsearchjLabel11 = new javax.swing.JLabel();
        SearchjLabel12 = new javax.swing.JLabel();
        Result1jLabel13 = new javax.swing.JLabel();
        Result2jLabel14 = new javax.swing.JLabel();
        RemarqjLabel8 = new javax.swing.JLabel();
        RemarqtextjLabel9 = new javax.swing.JLabel();
        savejButton8 = new javax.swing.JButton();
        updjButton9 = new javax.swing.JButton();
        Btnnew = new javax.swing.JButton();
        Tools_Panel = new javax.swing.JPanel();
        Tool_Panel_home = new javax.swing.JPanel();
        Label1 = new javax.swing.JLabel();
        Tool_Panal_Second = new javax.swing.JPanel();
        homeLabel2 = new javax.swing.JLabel();
        Tool_Panal_help = new javax.swing.JPanel();
        helpLabel3 = new javax.swing.JLabel();
        Tool_panal_exit = new javax.swing.JPanel();
        EXIT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        general_panel.setBackground(new java.awt.Color(255, 255, 255));
        general_panel.setName("general_panel"); // NOI18N

        GPanel_First.setBackground(new java.awt.Color(255, 255, 255));
        GPanel_First.setName("GPanel_First"); // NOI18N

        btnSAVEGeneral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/let/me/know/my/note/bookmark_20px.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("let/me/know/my/note/Bundle"); // NOI18N
        btnSAVEGeneral.setText(bundle.getString("DEP.btnSAVEGeneral.text")); // NOI18N
        btnSAVEGeneral.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSAVEGeneral.setName("btnSAVEGeneral"); // NOI18N

        btnUPDATECLASS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/let/me/know/my/note/update_user_20px.png"))); // NOI18N
        btnUPDATECLASS.setText(bundle.getString("DEP.btnUPDATECLASS.text")); // NOI18N
        btnUPDATECLASS.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnUPDATECLASS.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUPDATECLASS.setName("btnUPDATECLASS"); // NOI18N

        btnSerachSOMEONE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/let/me/know/my/note/google_web_search_20px.png"))); // NOI18N
        btnSerachSOMEONE.setText(bundle.getString("DEP.btnSerachSOMEONE.text")); // NOI18N
        btnSerachSOMEONE.setBorder(null);
        btnSerachSOMEONE.setName("btnSerachSOMEONE"); // NOI18N
        btnSerachSOMEONE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerachSOMEONEActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        GENERALjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Full name", "Module 1", "Module 2", "Module 3", "Module 4", "Module 5", "Module 6", "Module 7", "moyen "
            }
        ));
        GENERALjTable1.setName("GENERALjTable1"); // NOI18N
        GENERALjTable1.setRowHeight(22);
        jScrollPane1.setViewportView(GENERALjTable1);

        SEARCHTextField1.setText(bundle.getString("DEP.SEARCHTextField1.text")); // NOI18N
        SEARCHTextField1.setName("SEARCHTextField1"); // NOI18N
        SEARCHTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHTextField1ActionPerformed(evt);
            }
        });

        CLASSOFjTextField3.setText(bundle.getString("DEP.CLASSOFjTextField3.text")); // NOI18N
        CLASSOFjTextField3.setName("CLASSOFjTextField3"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setText(bundle.getString("DEP.jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setText(bundle.getString("DEP.jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setText(bundle.getString("DEP.jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setText(bundle.getString("DEP.jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setText(bundle.getString("DEP.jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        SEARCHSOMEONEjLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        SEARCHSOMEONEjLabel6.setText(bundle.getString("DEP.SEARCHSOMEONEjLabel6.text")); // NOI18N
        SEARCHSOMEONEjLabel6.setName("SEARCHSOMEONEjLabel6"); // NOI18N

        javax.swing.GroupLayout GPanel_FirstLayout = new javax.swing.GroupLayout(GPanel_First);
        GPanel_First.setLayout(GPanel_FirstLayout);
        GPanel_FirstLayout.setHorizontalGroup(
            GPanel_FirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GPanel_FirstLayout.createSequentialGroup()
                .addGroup(GPanel_FirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GPanel_FirstLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(GPanel_FirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GPanel_FirstLayout.createSequentialGroup()
                                .addComponent(CLASSOFjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUPDATECLASS))
                            .addComponent(jLabel4)))
                    .addGroup(GPanel_FirstLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(SEARCHSOMEONEjLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(GPanel_FirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GPanel_FirstLayout.createSequentialGroup()
                                .addComponent(SEARCHTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSerachSOMEONE, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(GPanel_FirstLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(171, 171, 171)
                                .addComponent(jLabel2)
                                .addGap(113, 113, 113)
                                .addComponent(jLabel3)))
                        .addGap(176, 176, 176)
                        .addComponent(btnSAVEGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(GPanel_FirstLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        GPanel_FirstLayout.setVerticalGroup(
            GPanel_FirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GPanel_FirstLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(GPanel_FirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSAVEGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(GPanel_FirstLayout.createSequentialGroup()
                        .addGroup(GPanel_FirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(GPanel_FirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SEARCHSOMEONEjLabel6)
                                .addComponent(SEARCHTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSerachSOMEONE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(GPanel_FirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GPanel_FirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUPDATECLASS)
                    .addGroup(GPanel_FirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(CLASSOFjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GPanel_help.setBackground(new java.awt.Color(102, 102, 102));
        GPanel_help.setName("GPanel_help"); // NOI18N

        jPanel3.setName("jPanel3"); // NOI18N

        jButton11.setBackground(new java.awt.Color(51, 51, 51));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText(bundle.getString("DEP.jButton11.text")); // NOI18N
        jButton11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton11.setName("jButton11"); // NOI18N

        jButton12.setBackground(new java.awt.Color(51, 51, 51));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText(bundle.getString("DEP.jButton12.text")); // NOI18N
        jButton12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton12.setName("jButton12"); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(646, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jPanel4.setName("jPanel4"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout GPanel_helpLayout = new javax.swing.GroupLayout(GPanel_help);
        GPanel_help.setLayout(GPanel_helpLayout);
        GPanel_helpLayout.setHorizontalGroup(
            GPanel_helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GPanel_helpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(275, 275, 275)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        GPanel_helpLayout.setVerticalGroup(
            GPanel_helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GPanel_helpLayout.createSequentialGroup()
                .addGroup(GPanel_helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GPanel_helpLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GPanel_helpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        GPanel_second.setBackground(new java.awt.Color(255, 255, 255));
        GPanel_second.setName("GPanel_second"); // NOI18N

        jPanelClass.setBackground(new java.awt.Color(102, 102, 102));
        jPanelClass.setName("jPanelClass"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        TECHERjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Teacher", "Class"
            }
        ));
        TECHERjTable.setName("TECHERjTable"); // NOI18N
        TECHERjTable.setRowHeight(23);
        jScrollPane2.setViewportView(TECHERjTable);

        btnEDITTECHER.setText(bundle.getString("DEP.btnEDITTECHER.text")); // NOI18N
        btnEDITTECHER.setName("btnEDITTECHER"); // NOI18N

        btnUPLOADTEACHER.setText(bundle.getString("DEP.btnUPLOADTEACHER.text")); // NOI18N
        btnUPLOADTEACHER.setName("btnUPLOADTEACHER"); // NOI18N

        CLASSjLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        CLASSjLabel.setForeground(new java.awt.Color(255, 255, 255));
        CLASSjLabel.setText(bundle.getString("DEP.CLASSjLabel.text")); // NOI18N
        CLASSjLabel.setName("CLASSjLabel"); // NOI18N

        javax.swing.GroupLayout jPanelClassLayout = new javax.swing.GroupLayout(jPanelClass);
        jPanelClass.setLayout(jPanelClassLayout);
        jPanelClassLayout.setHorizontalGroup(
            jPanelClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClassLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanelClassLayout.createSequentialGroup()
                        .addComponent(btnEDITTECHER, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addGap(35, 35, 35)
                        .addComponent(btnUPLOADTEACHER, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelClassLayout.createSequentialGroup()
                        .addComponent(CLASSjLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelClassLayout.setVerticalGroup(
            jPanelClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClassLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(CLASSjLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEDITTECHER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUPLOADTEACHER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        jPaneltecher.setBackground(new java.awt.Color(204, 204, 204));
        jPaneltecher.setName("jPaneltecher"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        MODULESjTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Module ", "Teacher"
            }
        ));
        MODULESjTable3.setName("MODULESjTable3"); // NOI18N
        MODULESjTable3.setRowHeight(23);
        jScrollPane3.setViewportView(MODULESjTable3);

        btnupdate.setText(bundle.getString("DEP.btnupdate.text")); // NOI18N
        btnupdate.setName("btnupdate"); // NOI18N

        btnsave.setText(bundle.getString("DEP.btnsave.text")); // NOI18N
        btnsave.setName("btnsave"); // NOI18N

        MODULESjLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        MODULESjLabel10.setText(bundle.getString("DEP.MODULESjLabel10.text")); // NOI18N
        MODULESjLabel10.setName("MODULESjLabel10"); // NOI18N

        jTextFieldsearch.setText(bundle.getString("DEP.jTextFieldsearch.text")); // NOI18N
        jTextFieldsearch.setName("jTextFieldsearch"); // NOI18N

        btnsearchjLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/let/me/know/my/note/google_web_search_20px.png"))); // NOI18N
        btnsearchjLabel11.setText(bundle.getString("DEP.btnsearchjLabel11.text")); // NOI18N
        btnsearchjLabel11.setName("btnsearchjLabel11"); // NOI18N

        SearchjLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        SearchjLabel12.setText(bundle.getString("DEP.SearchjLabel12.text")); // NOI18N
        SearchjLabel12.setName("SearchjLabel12"); // NOI18N

        Result1jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Result1jLabel13.setText(bundle.getString("DEP.Result1jLabel13.text")); // NOI18N
        Result1jLabel13.setName("Result1jLabel13"); // NOI18N

        Result2jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Result2jLabel14.setText(bundle.getString("DEP.Result2jLabel14.text")); // NOI18N
        Result2jLabel14.setName("Result2jLabel14"); // NOI18N

        javax.swing.GroupLayout jPaneltecherLayout = new javax.swing.GroupLayout(jPaneltecher);
        jPaneltecher.setLayout(jPaneltecherLayout);
        jPaneltecherLayout.setHorizontalGroup(
            jPaneltecherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneltecherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneltecherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MODULESjLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPaneltecherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchjLabel12)
                    .addGroup(jPaneltecherLayout.createSequentialGroup()
                        .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPaneltecherLayout.createSequentialGroup()
                        .addComponent(jTextFieldsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsearchjLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Result1jLabel13)
                    .addComponent(Result2jLabel14))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPaneltecherLayout.setVerticalGroup(
            jPaneltecherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneltecherLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPaneltecherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MODULESjLabel10)
                    .addComponent(SearchjLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPaneltecherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPaneltecherLayout.createSequentialGroup()
                        .addGroup(jPaneltecherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldsearch, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(btnsearchjLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52)
                        .addComponent(Result1jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Result2jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPaneltecherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnsave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnupdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        RemarqjLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        RemarqjLabel8.setText(bundle.getString("DEP.RemarqjLabel8.text")); // NOI18N
        RemarqjLabel8.setName("RemarqjLabel8"); // NOI18N

        RemarqtextjLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        RemarqtextjLabel9.setText(bundle.getString("DEP.RemarqtextjLabel9.text")); // NOI18N
        RemarqtextjLabel9.setName("RemarqtextjLabel9"); // NOI18N

        savejButton8.setText(bundle.getString("DEP.savejButton8.text")); // NOI18N
        savejButton8.setName("savejButton8"); // NOI18N

        updjButton9.setText(bundle.getString("DEP.updjButton9.text")); // NOI18N
        updjButton9.setName("updjButton9"); // NOI18N

        Btnnew.setText(bundle.getString("DEP.Btnnew.text")); // NOI18N
        Btnnew.setName("Btnnew"); // NOI18N

        javax.swing.GroupLayout GPanel_secondLayout = new javax.swing.GroupLayout(GPanel_second);
        GPanel_second.setLayout(GPanel_secondLayout);
        GPanel_secondLayout.setHorizontalGroup(
            GPanel_secondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GPanel_secondLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GPanel_secondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(GPanel_secondLayout.createSequentialGroup()
                        .addComponent(Btnnew, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updjButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(savejButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GPanel_secondLayout.createSequentialGroup()
                        .addComponent(jPanelClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(GPanel_secondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPaneltecher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RemarqjLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RemarqtextjLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        GPanel_secondLayout.setVerticalGroup(
            GPanel_secondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GPanel_secondLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GPanel_secondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GPanel_secondLayout.createSequentialGroup()
                        .addComponent(jPaneltecher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(RemarqjLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(RemarqtextjLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(GPanel_secondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GPanel_secondLayout.createSequentialGroup()
                                .addComponent(updjButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(savejButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btnnew, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanelClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout general_panelLayout = new javax.swing.GroupLayout(general_panel);
        general_panel.setLayout(general_panelLayout);
        general_panelLayout.setHorizontalGroup(
            general_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1449, Short.MAX_VALUE)
            .addGroup(general_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(general_panelLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(GPanel_second, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
            .addGroup(general_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(general_panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(GPanel_help, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(general_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(general_panelLayout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(GPanel_First, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(25, 25, 25)))
        );
        general_panelLayout.setVerticalGroup(
            general_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(general_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(general_panelLayout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(GPanel_second, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(6, 6, 6)))
            .addGroup(general_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(general_panelLayout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(GPanel_help, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(6, 6, 6)))
            .addGroup(general_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(general_panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(GPanel_First, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(general_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 1290, 770));

        Tools_Panel.setBackground(new java.awt.Color(204, 204, 255));
        Tools_Panel.setName("Tools_Panel"); // NOI18N
        Tools_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tool_Panel_home.setBackground(new java.awt.Color(255, 255, 255));
        Tool_Panel_home.setName("Tool_Panel_home"); // NOI18N
        Tool_Panel_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tool_Panel_homeMouseClicked(evt);
            }
        });
        Tool_Panel_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/let/me/know/my/note/home_25px.png"))); // NOI18N
        Label1.setText(bundle.getString("DEP.Label1.text")); // NOI18N
        Label1.setName("Label1"); // NOI18N
        Tool_Panel_home.add(Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        Tools_Panel.add(Tool_Panel_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 50, 50));

        Tool_Panal_Second.setBackground(new java.awt.Color(204, 204, 255));
        Tool_Panal_Second.setName("Tool_Panal_Second"); // NOI18N
        Tool_Panal_Second.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/let/me/know/my/note/registration_20px.png"))); // NOI18N
        homeLabel2.setText(bundle.getString("DEP.homeLabel2.text")); // NOI18N
        homeLabel2.setName("homeLabel2"); // NOI18N
        homeLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLabel2MouseClicked(evt);
            }
        });
        Tool_Panal_Second.add(homeLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 30, 28));

        Tools_Panel.add(Tool_Panal_Second, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 50, 50));

        Tool_Panal_help.setBackground(new java.awt.Color(204, 204, 255));
        Tool_Panal_help.setName("Tool_Panal_help"); // NOI18N

        helpLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helpLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/let/me/know/my/note/service_20px.png"))); // NOI18N
        helpLabel3.setText(bundle.getString("DEP.helpLabel3.text")); // NOI18N
        helpLabel3.setName("helpLabel3"); // NOI18N
        helpLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Tool_Panal_helpLayout = new javax.swing.GroupLayout(Tool_Panal_help);
        Tool_Panal_help.setLayout(Tool_Panal_helpLayout);
        Tool_Panal_helpLayout.setHorizontalGroup(
            Tool_Panal_helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(helpLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        Tool_Panal_helpLayout.setVerticalGroup(
            Tool_Panal_helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tool_Panal_helpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helpLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tools_Panel.add(Tool_Panal_help, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        Tool_panal_exit.setBackground(new java.awt.Color(204, 204, 255));
        Tool_panal_exit.setName("Tool_panal_exit"); // NOI18N

        EXIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/let/me/know/my/note/enter_25px.png"))); // NOI18N
        EXIT.setText(bundle.getString("DEP.EXIT.text")); // NOI18N
        EXIT.setName("EXIT"); // NOI18N
        EXIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXITMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Tool_panal_exitLayout = new javax.swing.GroupLayout(Tool_panal_exit);
        Tool_panal_exit.setLayout(Tool_panal_exitLayout);
        Tool_panal_exitLayout.setHorizontalGroup(
            Tool_panal_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tool_panal_exitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EXIT)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        Tool_panal_exitLayout.setVerticalGroup(
            Tool_panal_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tool_panal_exitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EXIT)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Tools_Panel.add(Tool_panal_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 50, 50));

        getContentPane().add(Tools_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tool_Panel_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tool_Panel_homeMouseClicked
        Tool_Panel_home.setBackground(new java.awt.Color(255,255,255));
        
        Tool_Panal_Second.setBackground(new java.awt.Color(204,204,255));
        Tool_Panal_help.setBackground(new java.awt.Color(204,204,255));
       // Panel4.setBackground(new java.awt.Color(204,204,255));
        Tool_panal_exit.setBackground(new java.awt.Color(204,204,255));
        
        
        general_panel.setVisible(true);
        GPanel_First.setVisible(true);
        GPanel_help.setVisible(false);
        GPanel_second.setVisible(false);
    }//GEN-LAST:event_Tool_Panel_homeMouseClicked

    private void homeLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabel2MouseClicked
        // TODO add your handling code here:
        Tool_Panal_Second.setBackground(new java.awt.Color(255,255,255));
        
        Tool_Panel_home.setBackground(new java.awt.Color(204,204,255));
        Tool_Panal_help.setBackground(new java.awt.Color(204,204,255));
        //Panel4.setBackground(new java.awt.Color(204,204,255));
        Tool_panal_exit.setBackground(new java.awt.Color(204,204,255));
        
        general_panel.setVisible(true);
        GPanel_First.setVisible(false);
        GPanel_second.setVisible(true);
        GPanel_help.setVisible(false);
    }//GEN-LAST:event_homeLabel2MouseClicked

    private void helpLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpLabel3MouseClicked
        // TODO add your handling code here:
        Tool_Panal_help.setBackground(new java.awt.Color(255,255,255));
        
        Tool_Panel_home.setBackground(new java.awt.Color(204,204,255));
        Tool_Panal_Second.setBackground(new java.awt.Color(204,204,255));
        //Panel4.setBackground(new java.awt.Color(204,204,255));
        Tool_panal_exit.setBackground(new java.awt.Color(204,204,255));
        
        general_panel.setVisible(true);
        GPanel_First.setVisible(false);
        GPanel_second.setVisible(false);
        GPanel_help.setVisible(true);
    }//GEN-LAST:event_helpLabel3MouseClicked

    private void btnSerachSOMEONEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerachSOMEONEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSerachSOMEONEActionPerformed

    private void SEARCHTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SEARCHTextField1ActionPerformed

    private void EXITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXITMouseClicked
        // TODO add your handling code here:
        new WHOis().setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_EXITMouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DEP().setVisible(true);
                
               //#4C4A48===rgb(76 74 72)
               //#F0F0F0===rgb()
               //BLUE [204,204,255]
               
            }
        });
    }
    
private void SetIconImage() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("LOGO.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnnew;
    private javax.swing.JTextField CLASSOFjTextField3;
    private javax.swing.JLabel CLASSjLabel;
    private javax.swing.JLabel EXIT;
    private javax.swing.JTable GENERALjTable1;
    private javax.swing.JPanel GPanel_First;
    private javax.swing.JPanel GPanel_help;
    private javax.swing.JPanel GPanel_second;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel MODULESjLabel10;
    private javax.swing.JTable MODULESjTable3;
    private javax.swing.JLabel RemarqjLabel8;
    private javax.swing.JLabel RemarqtextjLabel9;
    private javax.swing.JLabel Result1jLabel13;
    private javax.swing.JLabel Result2jLabel14;
    private javax.swing.JLabel SEARCHSOMEONEjLabel6;
    private javax.swing.JTextField SEARCHTextField1;
    private javax.swing.JLabel SearchjLabel12;
    private javax.swing.JTable TECHERjTable;
    private javax.swing.JPanel Tool_Panal_Second;
    private javax.swing.JPanel Tool_Panal_help;
    private javax.swing.JPanel Tool_Panel_home;
    private javax.swing.JPanel Tool_panal_exit;
    private javax.swing.JPanel Tools_Panel;
    private javax.swing.JButton btnEDITTECHER;
    private javax.swing.JButton btnSAVEGeneral;
    private javax.swing.JButton btnSerachSOMEONE;
    private javax.swing.JButton btnUPDATECLASS;
    private javax.swing.JButton btnUPLOADTEACHER;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel btnsearchjLabel11;
    private javax.swing.JButton btnupdate;
    private javax.swing.JPanel general_panel;
    private javax.swing.JLabel helpLabel3;
    private javax.swing.JLabel homeLabel2;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelClass;
    private javax.swing.JPanel jPaneltecher;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextFieldsearch;
    private javax.swing.JButton savejButton8;
    private javax.swing.JButton updjButton9;
    // End of variables declaration//GEN-END:variables
}
