/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package let.me.know.my.note;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.sql.*;


public class HOME extends javax.swing.JFrame {

    /**
     * Creates new form HOME
     */
    public HOME() {
        
        initComponents();
        
        this.setLocationRelativeTo(this);
    }
    static  DefaultTableModel model;
public static void addRowtotable (Object[] D_row){
         model =(DefaultTableModel) STUDENTjTable1.getModel();
            model.addRow(D_row);
        } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NOTEjTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        STUDENTjTable1 = new javax.swing.JTable();
        ID_TextField = new javax.swing.JTextField();
        EXNOTEjTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnEDIT = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        SERCHjTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        EXIT = new javax.swing.JButton();
        btnSAVE = new javax.swing.JButton();
        numberjLabel8 = new javax.swing.JLabel();
        classofjLabel9 = new javax.swing.JLabel();
        modulejLabel10 = new javax.swing.JLabel();
        btnHELP = new javax.swing.JButton();
        btnPUSH = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnSEARCH = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnUPDATE = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("jPanel1"); // NOI18N

        NOTEjTextField1.setName("NOTEjTextField1"); // NOI18N
        NOTEjTextField1.setSelectionStart(10);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        STUDENTjTable1.setFont(new java.awt.Font("Candara", 0, 11)); // NOI18N
        STUDENTjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "FULL NAME", "TEST", "EXAM", "Moyen"
            }
        ));
        STUDENTjTable1.setName("STUDENTjTable1"); // NOI18N
        STUDENTjTable1.setRowHeight(21);
        jScrollPane1.setViewportView(STUDENTjTable1);

        ID_TextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ID_TextField.setName("ID_TextField"); // NOI18N
        ID_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_TextFieldActionPerformed(evt);
            }
        });

        EXNOTEjTextField3.setName("EXNOTEjTextField3"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("let/me/know/my/note/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("HOME.jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jLabel2.setText(bundle.getString("HOME.jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jLabel3.setText(bundle.getString("HOME.jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setText(bundle.getString("HOME.jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText(bundle.getString("HOME.jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        btnEDIT.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        btnEDIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/let/me/know/my/note/edit_file_20px.png"))); // NOI18N
        btnEDIT.setText(bundle.getString("HOME.btnEDIT.text")); // NOI18N
        btnEDIT.setName("btnEDIT"); // NOI18N

        btnInsert.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/let/me/know/my/note/new_document_20px.png"))); // NOI18N
        btnInsert.setText(bundle.getString("HOME.btnInsert.text")); // NOI18N
        btnInsert.setName("btnInsert"); // NOI18N
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jLabel6.setText(bundle.getString("HOME.jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        SERCHjTextField4.setName("SERCHjTextField4"); // NOI18N
        SERCHjTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SERCHjTextField4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText(bundle.getString("HOME.jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        EXIT.setBackground(new java.awt.Color(76, 74, 72));
        EXIT.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        EXIT.setForeground(new java.awt.Color(255, 255, 255));
        EXIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/let/me/know/my/note/enter_20px.png"))); // NOI18N
        EXIT.setText(bundle.getString("HOME.EXIT.text")); // NOI18N
        EXIT.setName("EXIT"); // NOI18N
        EXIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXITMouseClicked(evt);
            }
        });
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        btnSAVE.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        btnSAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/let/me/know/my/note/bookmark_20px.png"))); // NOI18N
        btnSAVE.setText(bundle.getString("HOME.btnSAVE.text")); // NOI18N
        btnSAVE.setName("btnSAVE"); // NOI18N

        numberjLabel8.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        numberjLabel8.setText(bundle.getString("HOME.numberjLabel8.text")); // NOI18N
        numberjLabel8.setName("numberjLabel8"); // NOI18N

        classofjLabel9.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        classofjLabel9.setText(bundle.getString("HOME.classofjLabel9.text")); // NOI18N
        classofjLabel9.setName("classofjLabel9"); // NOI18N

        modulejLabel10.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        modulejLabel10.setText(bundle.getString("HOME.modulejLabel10.text")); // NOI18N
        modulejLabel10.setName("modulejLabel10"); // NOI18N

        btnHELP.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        btnHELP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/let/me/know/my/note/information_20px.png"))); // NOI18N
        btnHELP.setText(bundle.getString("HOME.btnHELP.text")); // NOI18N
        btnHELP.setName("btnHELP"); // NOI18N
        btnHELP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHELPActionPerformed(evt);
            }
        });

        btnPUSH.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        btnPUSH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/let/me/know/my/note/paper_plane_20px.png"))); // NOI18N
        btnPUSH.setText(bundle.getString("HOME.btnPUSH.text")); // NOI18N
        btnPUSH.setName("btnPUSH"); // NOI18N
        btnPUSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPUSHActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel11.setText(bundle.getString("HOME.jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        btnSEARCH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/let/me/know/my/note/google_web_search_20px.png"))); // NOI18N
        btnSEARCH.setText(bundle.getString("HOME.btnSEARCH.text")); // NOI18N
        btnSEARCH.setBorder(null);
        btnSEARCH.setName("btnSEARCH"); // NOI18N

        jLabel12.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jLabel12.setText(bundle.getString("HOME.jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel13.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jLabel13.setText(bundle.getString("HOME.jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel14.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jLabel14.setText(bundle.getString("HOME.jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        jLabel15.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jLabel15.setText(bundle.getString("HOME.jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel16.setText(bundle.getString("HOME.jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel17.setText(bundle.getString("HOME.jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

        btnUPDATE.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        btnUPDATE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/let/me/know/my/note/update_user_20px.png"))); // NOI18N
        btnUPDATE.setText(bundle.getString("HOME.btnUPDATE.text")); // NOI18N
        btnUPDATE.setName("btnUPDATE"); // NOI18N
        btnUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel18.setText(bundle.getString("HOME.jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(numberjLabel8)
                        .addComponent(jLabel5)
                        .addComponent(classofjLabel9)
                        .addComponent(modulejLabel10)
                        .addComponent(EXIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSAVE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHELP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPUSH, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                        .addComponent(btnUPDATE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(SERCHjTextField4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnEDIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel6)
                                .addComponent(jLabel16))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NOTEjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ID_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EXNOTEjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addGap(108, 108, 108)
                .addComponent(jLabel17)
                .addGap(28, 28, 28)
                .addComponent(classofjLabel9)
                .addGap(18, 18, 18)
                .addComponent(numberjLabel8)
                .addGap(18, 18, 18)
                .addComponent(modulejLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(31, 31, 31)
                .addComponent(btnUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnPUSH, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnSAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnHELP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SERCHjTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel11)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel6)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel2)
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(EXNOTEjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ID_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(NOTEjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ID_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_TextFieldActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        // TODO add your handling code here:
        new WHOis().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EXITActionPerformed

    private void btnHELPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHELPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHELPActionPerformed

    private void SERCHjTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SERCHjTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SERCHjTextField4ActionPerformed

    private void btnUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEActionPerformed
        // public static ArrayList<Attribute> getpersons(){
        System.out.println("hhhhhhooooo");
        DB db= new DB();
        db.getConnection();
        Connection conn= db.getConnection();
        Statement stmt;
       // ArrayList<Attribute>  personlist =new ArrayList();
      
        try{
            stmt=conn.createStatement();
            ResultSet rs =stmt.executeQuery("select id,student_name from student_info");
            while(rs.next()){//next() bcause other data going in rs(resultset)
               Attribute person =new Attribute();
               person.setId(rs.getInt("id"));
               person.setStudent_name(rs.getString("student_name"));
               //person.setAge(rs.getInt("age"));
             //  personlist.add(person);
               
               addRowtotable(new Object []{ person.getId() ,person.getStudent_name(),null, null ,null});
            }
            conn.close();
            //return personlist;
        }catch(SQLException ex){
            ex.printStackTrace();
        }
        //return null;
        
        
   // }
    }//GEN-LAST:event_btnUPDATEActionPerformed

    private void EXITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXITMouseClicked
        // TODO add your handling code here:
       // new dep_mode().setVisible(true);
    }//GEN-LAST:event_EXITMouseClicked

    private void btnPUSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPUSHActionPerformed
 DB db= new DB();
        db.getConnection();        // TODO add your handling code here:
    }//GEN-LAST:event_btnPUSHActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME().setVisible(true);
               //#4C4A48===rgb(76 74 72)
               //#F0F0F0===rgb()
               
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXIT;
    private javax.swing.JTextField EXNOTEjTextField3;
    private javax.swing.JTextField ID_TextField;
    private javax.swing.JTextField NOTEjTextField1;
    private javax.swing.JTextField SERCHjTextField4;
    private static javax.swing.JTable STUDENTjTable1;
    private javax.swing.JButton btnEDIT;
    private javax.swing.JButton btnHELP;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnPUSH;
    private javax.swing.JButton btnSAVE;
    private javax.swing.JButton btnSEARCH;
    private static javax.swing.JButton btnUPDATE;
    private javax.swing.JLabel classofjLabel9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel modulejLabel10;
    private javax.swing.JLabel numberjLabel8;
    // End of variables declaration//GEN-END:variables
}
