/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.note;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import static my.note.DEP.GHOMETable;
import static my.note.DEP.addRowtotable;

/**
 *
 * @author Yahia Benotmane
 */
public class STUDENT extends javax.swing.JFrame {

    /**
     * Creates new form STUDENT
     */
    public STUDENT() {
        initComponents();
         this.setLocationRelativeTo(this);
    }
static  DefaultTableModel model;
public static void addRowtotable (Object[] D_row){
         model =(DefaultTableModel) BULjTable1.getModel();
            model.addRow(D_row);
        }
public void clearTable2()
{
   
    DefaultTableModel dtm = (DefaultTableModel) GHOMETable.getModel();
dtm.setRowCount(0);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SUSERNAMELabel = new javax.swing.JLabel();
        SID = new javax.swing.JLabel();
        REMARKTEXT = new javax.swing.JLabel();
        REMARK = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BULjTable1 = new javax.swing.JTable();
        INPUTfeedback = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        EXITicon = new javax.swing.JLabel();
        INFOicon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        SUSERNAMELabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SUSERNAMELabel.setForeground(new java.awt.Color(51, 51, 51));
        SUSERNAMELabel.setText("Hello , Mr Username");

        SID.setText("Your id :");

        REMARKTEXT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        REMARKTEXT.setForeground(new java.awt.Color(51, 51, 51));
        REMARKTEXT.setText("Your remark");

        REMARK.setText("remark");

        BULjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Module name", "Note test", "Note examn", "Module moyenne"
            }
        ));
        BULjTable1.setRowHeight(45);
        jScrollPane1.setViewportView(BULjTable1);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/note/paper_plane_20px.png"))); // NOI18N
        jButton1.setText("Feedback");

        EXITicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/note/enter_25px.png"))); // NOI18N
        EXITicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXITiconMouseClicked(evt);
            }
        });

        INFOicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/note/help_20px.png"))); // NOI18N
        INFOicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                INFOiconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SUSERNAMELabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(INFOicon))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EXITicon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(INPUTfeedback)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SID)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(REMARKTEXT)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(REMARK)))))
                        .addContainerGap(28, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INFOicon)
                    .addComponent(SUSERNAMELabel))
                .addGap(18, 18, 18)
                .addComponent(SID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(REMARKTEXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(REMARK)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(EXITicon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(INPUTfeedback))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EXITiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXITiconMouseClicked
        // TODO add your handling code here:
       new DEP().setVisible(true);
       this.dispose();
        
    }//GEN-LAST:event_EXITiconMouseClicked

    private void INFOiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INFOiconMouseClicked
        clearTable2();
        System.out.println("updating...........");
        DB db= new DB();
        db.getConnection();
        Connection conn= db.getConnection();
        Statement stmt;
       // ArrayList<Attribute>  personlist =new ArrayList();
      
        try{
            stmt=conn.createStatement();
            ResultSet rs =stmt.executeQuery("select id,student_name,arabic_average from arabic");
            while(rs.next()){//next() bcause other data going in rs(resultset)
               Attribute person =new Attribute();
               person.setId(rs.getInt("id"));
               person.setStudent_name(rs.getString("student_name"));
               person.setAverage(rs.getString("arabic_average"));
               //person.setAge(rs.getInt("age"));
             //  personlist.add(person);
               
               //addRowtotable(new Object []{ person.getId() ,person.getStudent_name(),person.getAverage(), null ,null,null ,null,null ,null,null });
               STUDENT.addRowtotable(new Object []{ null,null,null ,person.getAverage() });
            }
            conn.close();
            //return personlist;
        }catch(SQLException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_INFOiconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(STUDENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(STUDENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(STUDENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(STUDENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new STUDENT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable BULjTable1;
    private javax.swing.JLabel EXITicon;
    private javax.swing.JLabel INFOicon;
    private javax.swing.JTextField INPUTfeedback;
    private javax.swing.JLabel REMARK;
    private javax.swing.JLabel REMARKTEXT;
    private javax.swing.JLabel SID;
    private javax.swing.JLabel SUSERNAMELabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
